namespace Entitas.CodeGeneration.Plugins
{
	public class AddFileHeaderPostProcessor : IPostProcessor, ICodeGenerationPlugin
	{
		public const string AUTO_GENERATED_HEADER_FORMAT = "//------------------------------------------------------------------------------\n// <auto-generated>\n//     This code was generated by {0}.\n//\n//     Changes to this file may cause incorrect behavior and will be lost if\n//     the code is regenerated.\n// </auto-generated>\n//------------------------------------------------------------------------------\n";

		public string name
		{
			get
			{
				return "Add file header";
			}
		}

		public int priority
		{
			get
			{
				return 0;
			}
		}

		public bool isEnabledByDefault
		{
			get
			{
				return true;
			}
		}

		public bool runInDryMode
		{
			get
			{
				return true;
			}
		}

		public CodeGenFile[] PostProcess(CodeGenFile[] files)
		{
			foreach (CodeGenFile codeGenFile in files)
			{
				codeGenFile.fileContent = string.Format("//------------------------------------------------------------------------------\n// <auto-generated>\n//     This code was generated by {0}.\n//\n//     Changes to this file may cause incorrect behavior and will be lost if\n//     the code is regenerated.\n// </auto-generated>\n//------------------------------------------------------------------------------\n", codeGenFile.generatorName) + codeGenFile.fileContent;
			}
			return files;
		}
	}
}
